name: "Grafana Alloy"
description: "Send metrics & logs to Grafana Cloud or your own Grafana observability stack"
version: "0.0.2"
slug: "grafana_alloy"
init: false
arch:
  - amd64
  - aarch64
options:
  alloy_config: null
schema:
  alloy_config: str
homeassistant_api: true
map:
  - type: homeassistant_config
    path: /custom/config
  - addon_config:rw
ports:
  80/tcp: null
ports_description:
  80/tcp: "Debug UI"
webui: "http://[HOST]:[PORT:12345]/"
ingress: true
ingress_port: 12345
image: "ghcr.io/spechtlabs/hass-addon-grafana-alloy-{arch}"
