blueprint:
  name: Philips Tap Dial Switch (ZHA)
  description:
    Control lights with a Philips Hue Tap Switch. Use the four buttons
    to control up to four light(s) with an on/off toggle. The dial can be used to
    dim the most recently used light.
  source_url: https://github.com/SpechtLabs/homeassistant-addons/blob/main/blueprints/hue_tab_dial_zha.yaml
  domain: automation
  input:
    remote:
      name: Philips Hue Tap Switch
      selector:
        device:
          integration: zha
          manufacturer: Signify Netherlands B.V.
          model: RDM002
          multiple: false
    dim_scale:
      name: Diming Scale
      description:
        Scale factor for the dimming. This value will be multiplied by
        the value given from the dial. So lower number, more gradual dimming. Larger
        number, faster dimming.
      default: 1.0
      selector:
        number:
          min: 0.0
          max: 5.0
          step: 0.01
          mode: slider
    dimmer_light:
      name: Dimmer Light
      description: The light(s) to control with the dimmer dial.
      selector:
        target:
          entity:
            - {}
    button_1_short:
      name: Button 1 - single click
      description: Action to run on single click on Button 1
      default: []
      selector:
        action: {}
    button_1_double:
      name: Button 1 - double click
      description: Action to run on double click on Button 1
      default: []
      selector:
        action: {}
    button_1_long_hold:
      name: Button 1 - long press (hold)
      description: Action to run on holding down on Button 1
      default: []
      selector:
        action: {}
    button_1_long_release:
      name: Button 1 - long press (release)
      description: Action to run on releasing a long-click on Button 1
      default: []
      selector:
        action: {}
    button_2_short:
      name: Button 2 - single click
      description: Action to run on single click on Button 2
      default: []
      selector:
        action: {}
    button_2_double:
      name: Button 2 - double click
      description: Action to run on double click on Button 2
      default: []
      selector:
        action: {}
    button_2_long_hold:
      name: Button 2 - long press (hold)
      description: Action to run on holding down on Button 2
      default: []
      selector:
        action: {}
    button_2_long_release:
      name: Button 2 - long press (release)
      description: Action to run on releasing a long-click on Button 2
      default: []
      selector:
        action: {}
    button_3_short:
      name: Button 3 - single click
      description: Action to run on single click on Button 3
      default: []
      selector:
        action: {}
    button_3_double:
      name: Button 3 - double click
      description: Action to run on double click on Button 3
      default: []
      selector:
        action: {}
    button_3_long_hold:
      name: Button 3 - long press (hold)
      description: Action to run on holding down on Button 3
      default: []
      selector:
        action: {}
    button_3_long_release:
      name: Button 3 - long press (release)
      description: Action to run on releasing a long-click on Button 3
      default: []
      selector:
        action: {}
    button_4_short:
      name: Button 4 - single click
      description: Action to run on single click on Button 4
      default: []
      selector:
        action: {}
    button_4_double:
      name: Button 4 - double click
      description: Action to run on double click on Button 4
      default: []
      selector:
        action: {}
    button_4_long_hold:
      name: Button 4 - long press (hold)
      description: Action to run on holding down on Button 4
      default: []
      selector:
        action: {}
    button_4_long_release:
      name: Button 4 - long press (release)
      description: Action to run on releasing a long-click on Button 4
      default: []
      selector:
        action: {}
variables:
  dim_scale: !input dim_scale
mode: restart
triggers:
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: 3588070feb3a8ab87fcd834b52ef01b0
actions:
  - variables:
      command: "{{ trigger.event.data.command }}"
      args: "{{ trigger.event.data.args }}"
      params: "{{ trigger.event.data.params }}"
      scene: "{{ trigger.event.data.params.scene_id }}"
      step_mode: "{{ trigger.event.data.params.step_mode }}"
      step_size: "{{ trigger.event.data.params.step_size }}"
  - choose:
      - conditions:
          - "{{ command == 'button_1_short_release' }}"
        sequence:
          - choose: []
            default: !input button_1_short
        alias: Button 1 - Short press
      - conditions:
          - "{{ command == 'button_1_double_press' }}"
        sequence:
          - choose: []
            default: !input button_1_double
        alias: Button 1 - Double press
      - conditions:
          - "{{ command == 'button_1_hold' }}"
        sequence:
          - choose: []
            default: !input button_1_long_hold
        alias: Button 1 - Long press (hold)
      - conditions:
          - "{{ command == 'button_1_hold' }}"
        sequence:
          - choose: []
            default: !input button_1_long_release
        alias: Button 1 - Long press (release)
      - conditions:
          - "{{ command == 'button_2_short_release' }}"
        sequence:
          - choose: []
            default: !input button_2_short
        alias: Button 2 - Short press
      - conditions:
          - "{{ command == 'button_2_double_press' }}"
        sequence:
          - choose: []
            default: !input button_2_short
        alias: Button 2 - Double press
      - conditions:
          - "{{ command == 'button_2_hold' }}"
        sequence:
          - choose: []
            default: !input button_2_short
        alias: Button 2 - Long press (hold)
      - conditions:
          - "{{ command == 'button_2_hold' }}"
        sequence:
          - choose: []
            default: !input button_2_short
        alias: Button 2 - Long press (release)
      - conditions:
          - "{{ command == 'button_3_short_release' }}"
        sequence:
          - choose: []
            default: !input button_3_short
        alias: Button 3 - Short press
      - conditions:
          - "{{ command == 'button_3_double_press' }}"
        sequence:
          - choose: []
            default: !input button_3_short
        alias: Button 3 - Double press
      - conditions:
          - "{{ command == 'button_3_hold' }}"
        sequence:
          - choose: []
            default: !input button_3_short
        alias: Button 3 - Long press (hold)
      - conditions:
          - "{{ command == 'button_3_hold' }}"
        sequence:
          - choose: []
            default: !input button_3_short
        alias: Button 3 - Long press (release)
      - conditions:
          - "{{ command == 'button_4_short_release' }}"
        sequence:
          - choose: []
            default: !input button_4_short
        alias: Button 4 - Short press
      - conditions:
          - "{{ command == 'button_4_double_press' }}"
        sequence:
          - choose: []
            default: !input button_4_short
        alias: Button 4 - Double press
      - conditions:
          - "{{ command == 'button_4_hold' }}"
        sequence:
          - choose: []
            default: !input button_4_short
        alias: Button 4 - Long press (hold)
      - conditions:
          - "{{ command == 'button_4_hold' }}"
        sequence:
          - choose: []
            default: !input button_4_short
        alias: Button 4 - Long press (release)
      - conditions:
          - "{{ command == 'step_with_on_off' }}"
          - "{{ step_mode == 'StepMode.Up' }}"
        sequence:
          - service: light.turn_on
            target: !input dimmer_light
            data:
              brightness_step_pct: "{{ step_size | multiply(dim_scale) }}"
              transition: 1
        alias: Dim Up
      - conditions:
          - "{{ command == 'step_with_on_off' }}"
          - "{{ step_mode == 'StepMode.Down' }}"
        sequence:
          - service: light.turn_on
            target: !input dimmer_light
            data:
              brightness_step_pct: "{{ -step_size | multiply(dim_scale) }}"
              transition: 1
        alias: Dim Down
